### ISSUE TITLE
你的项目不好找啊，给几个建议

### ISSUE THREAD

**Issue by Bian-Sh** [killop/UnityResourceSolution#3]
你的项目名称啥的巧妙的与 assetbundle 错开，这样就算star 了这个项目想根据印象找到还是有点难度
建议在项目 about 下给几个 关键字，比如：bundle、assetbundle 、ab 这样 （有配图）
![image](https://user-images.githubusercontent.com/24520547/218649257-0e646dab-877c-4c47-9213-a8e0ccc3ce32.png)

**Comment by killop** [comment]
收到 马上改
